# Site settings
title: Sally's Sand Box
header-img: img/home-bg.png
email: szasloff@gmail.com
copyright_name: SallyZ12
description: > # this means to ignore newlines until "baseurl:"
  Tech is Fun!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SallyZ12
learn_profile: SallyZ12
email_username: szasloff@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
